# Generated by Django 5.2 on 2025-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0005_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Earbuds', 'EARBUDS'), ('Earphones', 'EARPHONES'), ('Headsets', 'HEADSETS'), ('Headphones', 'HEADPHONES'), ('Peripherals', 'PERIPHERALS'), ('Mouse', 'MOUSE'), ('keyboard', 'KEYBOARD'), ('Gaming', 'GAMING'), ('Mic', 'MIC'), ('Camera', 'CAMERA')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='not_paid', max_length=20),
        ),
    ]
