# Generated by Django 5.2 on 2025-05-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0008_transaction_product_alter_product_seller'),
        ('core', '0003_remove_customuser_is_seller_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.seller'),
        ),
    ]
