# Generated by Django 5.2 on 2025-05-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0009_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
    ]
