# Generated by Django 5.2 on 2025-05-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_customuser_is_seller_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
