# Generated by Django 5.2 on 2025-05-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartify', '0010_remove_product_seller_remove_transaction_product'),
        ('core', '0004_alter_seller_shop_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
